<a href="https://colab.research.google.com/github/nikhilkoduvalli/Machine_Learning/blob/main/tennis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
outlook=['sunny','sunny','overcast','rainy','rainy','rainy',
         'overcast','sunny','sunny','rainy','sunny',
         'overcast','overcast','rainy']
temperature=['hot','hot','hot','mild','cool','cool','cool','mild',
             'cool','mild','mild','mild','hot','mild']
humidity=['high','high','high','high','normal','normal',
          'normal','high','normal','normal','normal','high','normal','high']

wind=['weak','strong','weak','weak','weak','strong','strong','weak',
      'weak','weak','strong','strong','weak','strong']

play=['no','no','yes','yes','yes','no','yes','no','yes','yes',
      'yes','yes','yes','no']


In [2]:
#encoding
#1.label encoding
#2.One-Hot encoding
#3.get dummies



#label encoding
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
outlook_encoded=lab.fit_transform(outlook)
outlook_encoded

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [3]:

temp_encoder=lab.fit_transform(temperature)
temp_encoder

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [4]:

humidity_encoder=lab.fit_transform(humidity)
humidity_encoder

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0])

In [5]:
wind_encoder=lab.fit_transform(wind)
wind_encoder

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0])

In [6]:
#zip

feature=list(zip(outlook_encoded,temp_encoder,humidity_encoder,wind_encoder))
feature

[(2, 1, 0, 1),
 (2, 1, 0, 0),
 (0, 1, 0, 1),
 (1, 2, 0, 1),
 (1, 0, 1, 1),
 (1, 0, 1, 0),
 (0, 0, 1, 0),
 (2, 2, 0, 1),
 (2, 0, 1, 1),
 (1, 2, 1, 1),
 (2, 2, 1, 0),
 (0, 2, 0, 0),
 (0, 1, 1, 1),
 (1, 2, 0, 0)]

In [7]:
#model creation(navebase)

#3 types of classifiers
#1.gaussion             ========>Continues data(if the data are alrerady numeric )
#2.multinomial          ========>Descreate data(if the data contain objects)
#3.burnoali             ========>Both for continues and descreate data


from sklearn.naive_bayes import MultinomialNB,GaussianNB
model=MultinomialNB()
model.fit(feature,play)



MultinomialNB()

In [8]:
print(model.predict([[2,0,0,0]]))

['no']
